### ISSUE TITLE
Exec list is currently wrong

### ISSUE THREAD

**Issue by the-Bruce** [dixonary/amphi-cloud-functions#2]
Since the latest election, the users marked as exec do not align with current exec. (although I'm not complaining at my current over perms...) 

This in the short term would be a list update here: https://github.com/dixonary/amphi-cloud-functions/blob/32f645b13f007fe576ce689286177b8bd084ee9d/src/index.ts#L173 
(current exec are 
```
1807683 | Scott
1833194 | John
1915915 | Keegan
2003030 | shadow
2008405 | Koala
2014020 | Leo
2041635 | Skiros
```
and Pres pending)

In the long term, this probably wants to be a call to the api being introduced in https://github.com/UWCS/uwcs-dextre/pull/6, specifically the `/api/profile/roles/` (requiring the `roles` scope). 

Sidenote, the `lanapp` scope and `/api/me/` should also be retired for the more general `profile` scope and `/api/profile/` endpoint, which has more accurate permission info (doesn't explicitly mention LANs). The `profile` and `lanapp` endpoints are the same (`lanapp` only left for compatibility), so changeover shouldn't be hard.

**Comment by dixonary** [comment]
I have now set the `isAdmin` flag for all users who have previously opened Amphi (it only populates a user profile once a user has visited the site at least once). I think Keegan is the only exec member who doesn't have a profile yet. I've also unset it for all ex-exec except for you and me (it is very convenient to have a reliable person to sanity check the back-of-house stuff!)

I will make the switch from `lanapp` to `profile` on the backend now - I think that is a simple text replace in the cloud functions.

**Comment by dixonary** [comment]
I have now also specified the complete set of "current" admins in cloud functions, so when Keegan's profile is created the `isAdmin` flag should be set automatically.

**Comment by dixonary** [comment]
Switching `lanapp` to `profile` throws an invalid scope error. Has this been merged yet? In the meantime i'll undo.

**Comment by joshdavies14** [comment]
Hello from me! That PR should now be merged and live on the site (sorry it took so long!), so hopefully any changes you want to make re this might work now (lmk if not and I can investigate) :)

**Comment by dixonary** [comment]
Thanks! I will get this updated and working before the next LAN/WAN.

**Comment by the-Bruce** [comment]
This has now been resolved using the new endpoint.
